import { useCallback, useEffect, useMemo, useState } from "react";
import { FiArrowRight, FiCheck, FiClock, FiLogIn, FiLogOut, FiPackage, FiRefreshCw, FiTruck, FiX } from "react-icons/fi";
import { supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";
import type { OrderStatus } from "../lib/database.types";

interface DashboardOrder { id:string; order_number:string; user_id:string; status:OrderStatus; subtotal:number; delivery_fee:number; total:number; fulfillment:"delivery"|"pickup"; formatted_address:string|null; phone:string; customer_name:string|null; notes:string|null; created_at:string; updated_at:string; order_items?:Array<{id:string;product_name:string;quantity:number;unit_price:number;total:number}>; }
type Filter="all"|"pending"|"preparing"|"ready"|"out_for_delivery"|"delivered";
const STATUS_LABELS:Record<OrderStatus,string>={pending:"جديد",confirmed:"مؤكد",preparing:"قيد التحضير",ready:"جاهز",out_for_delivery:"بالطريق",delivered:"مكتمل",cancelled:"ملغي"};
const NEXT_STATUS:Partial<Record<OrderStatus,OrderStatus>>={pending:"confirmed",confirmed:"preparing",preparing:"ready",ready:"out_for_delivery",out_for_delivery:"delivered"};
const money=(v:number)=>`${Number(v||0).toLocaleString("ar-IQ")} د.ع`;
const statusClass=(s:OrderStatus)=>s==="pending"?"border-red/30 bg-red/10 text-red-200":s==="preparing"||s==="confirmed"?"border-gold/30 bg-gold/10 text-gold":s==="ready"||s==="out_for_delivery"?"border-blue-400/30 bg-blue-400/10 text-blue-200":s==="delivered"?"border-green-400/30 bg-green-400/10 text-green-300":"border-white/10 bg-white/5 text-ivory-mute";

export default function RestaurantDashboard(){
 const {user,signOut,loading:authLoading}=useAuth(); const [authorized,setAuthorized]=useState<boolean|null>(null); const [orders,setOrders]=useState<DashboardOrder[]>([]); const [filter,setFilter]=useState<Filter>("all"); const [loading,setLoading]=useState(true); const [busyId,setBusyId]=useState<string|null>(null); const [error,setError]=useState("");
 const checkAccess=useCallback(async()=>{if(!user){setAuthorized(false);return;} const {data,error:e}=await supabase.from("restaurant_staff").select("user_id").eq("user_id",user.id).eq("active",true).maybeSingle();setAuthorized(!e&&!!data);},[user]);
 const loadOrders=useCallback(async()=>{setLoading(true);setError("");const {data,error:e}=await supabase.from("orders").select("*, order_items(*)").order("created_at",{ascending:false}).limit(100);if(e)setError(e.message);else setOrders((data||[]) as DashboardOrder[]);setLoading(false);},[]);
 useEffect(()=>{checkAccess()},[checkAccess]);
 useEffect(()=>{if(!authorized)return;loadOrders();const c=supabase.channel("restaurant-orders").on("postgres_changes",{event:"*",schema:"public",table:"orders"},()=>loadOrders()).subscribe();return()=>{supabase.removeChannel(c)}},[authorized,loadOrders]);
 const updateStatus=async(order:DashboardOrder,status:OrderStatus)=>{if(busyId)return;setBusyId(order.id);setError("");const {error:e}=await supabase.from("orders").update({status,updated_at:new Date().toISOString()} as never).eq("id",order.id);if(e)setError(e.message);else setOrders(p=>p.map(x=>x.id===order.id?{...x,status}:x));setBusyId(null)};
 const visible=useMemo(()=>filter==="all"?orders:orders.filter(o=>o.status===filter),[orders,filter]); const today=new Date().toDateString(); const todayOrders=orders.filter(o=>new Date(o.created_at).toDateString()===today&&o.status!=="cancelled"); const revenue=todayOrders.reduce((s,o)=>s+o.total,0); const active=orders.filter(o=>["pending","confirmed","preparing","ready","out_for_delivery"].includes(o.status)).length;
 if(authLoading||authorized===null)return <div className="grid min-h-screen place-items-center bg-bg text-ivory"><FiRefreshCw className="animate-spin"/></div>;
 if(!user)return <DashboardLogin/>;
 if(!authorized)return <AccessScreen title="الحساب غير مصرح" description="سجلت الدخول بنجاح، لكن هذا الحساب ليس ضمن موظفي المطعم. أضف الحساب إلى restaurant_staff من Supabase." userId={user.id}/>;
 return <div dir="rtl" className="min-h-screen bg-bg text-ivory"><header className="sticky top-0 z-20 border-b border-white/[.08] bg-bg/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gold text-bg"><FiPackage/></div><div><p className="font-display text-lg">معلم الشاورما</p><p className="text-xs text-ivory-mute">Restaurant Command Center</p></div></div><div className="flex items-center gap-2"><button onClick={loadOrders} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5"><FiRefreshCw size={16}/></button><button onClick={()=>signOut()} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-ivory-mute"><FiLogOut/> خروج</button></div></div></header><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:py-8">{error&&<div className="flex items-center justify-between rounded-2xl border border-red/30 bg-red/10 px-4 py-3 text-sm"><span>{error}</span><button onClick={()=>setError("")}><FiX/></button></div>}<section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={<FiPackage/>} label="طلبات اليوم" value={String(todayOrders.length)}/><Metric icon={<FiClock/>} label="طلبات نشطة" value={String(active)}/><Metric icon={<FiCheck/>} label="مكتملة" value={String(todayOrders.filter(o=>o.status==="delivered").length)}/><Metric icon={<FiTruck/>} label="مبيعات اليوم" value={money(revenue)}/></section><section className="rounded-3xl border border-white/[.08] bg-surface/70 p-4 sm:p-5"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="font-display text-xl">الطلبات</h1><p className="text-xs text-ivory-mute">تتحدث تلقائياً عند وصول طلب جديد</p></div><div className="flex gap-2 overflow-x-auto pb-1">{(["all","pending","preparing","ready","out_for_delivery","delivered"] as Filter[]).map(k=><button key={k} onClick={()=>setFilter(k)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs ${filter===k?"bg-gold text-bg":"bg-white/5 text-ivory-mute"}`}>{k==="all"?"الكل":STATUS_LABELS[k as OrderStatus]}</button>)}</div></div>{loading?<div className="grid min-h-52 place-items-center"><FiRefreshCw className="animate-spin text-gold"/></div>:visible.length===0?<div className="grid min-h-52 place-items-center rounded-2xl border border-dashed border-white/10 text-sm text-ivory-mute">ماكو طلبات بهالحالة</div>:<div className="grid gap-3 lg:grid-cols-2">{visible.map(o=><OrderCard key={o.id} order={o} busy={busyId===o.id} onStatus={updateStatus}/>)}</div>}</section></main></div>;
}
function DashboardLogin(){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const login=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError("");const {error:e2}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(e2)setError(e2.message);setBusy(false)};return <div dir="rtl" className="grid min-h-screen place-items-center bg-bg px-5 text-ivory"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/[.08] bg-surface p-7 shadow-2xl"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-gold text-bg"><FiPackage size={24}/></div><h1 className="text-center font-display text-2xl">دخول لوحة المطعم</h1><p className="mt-2 text-center text-sm text-ivory-mute">لصاحب المطعم والموظفين المصرح لهم فقط</p><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required placeholder="البريد الإلكتروني" className="mt-6 w-full rounded-xl border border-white/10 bg-bg px-4 py-3 text-sm"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required placeholder="كلمة المرور" className="mt-3 w-full rounded-xl border border-white/10 bg-bg px-4 py-3 text-sm"/>{error&&<p className="mt-3 rounded-xl border border-red/20 bg-red/10 p-3 text-xs text-red-200">تعذر تسجيل الدخول: {error}</p>}<button disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gold px-4 py-3 font-bold text-bg disabled:opacity-50">{busy?<FiRefreshCw className="animate-spin"/>:<FiLogIn/>} دخول</button><a href="/" className="mt-4 flex items-center justify-center gap-2 text-xs text-ivory-mute"><FiArrowRight/> العودة للموقع</a></form></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-white/[.08] bg-surface/70 p-4"><div className="mb-3 flex items-center gap-2 text-gold">{icon}<span className="text-xs text-ivory-mute">{label}</span></div><p className="font-display text-xl sm:text-2xl">{value}</p></div>}
function OrderCard({order,busy,onStatus}:{order:DashboardOrder;busy:boolean;onStatus:(o:DashboardOrder,s:OrderStatus)=>void}){const next=NEXT_STATUS[order.status];return <article className="rounded-2xl border border-white/[.08] bg-bg/60 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-display">#{order.order_number}</span><span className={`rounded-full border px-2 py-1 text-[10px] ${statusClass(order.status)}`}>{STATUS_LABELS[order.status]}</span></div><p className="mt-1 text-xs text-ivory-mute">{new Date(order.created_at).toLocaleString("ar-IQ",{dateStyle:"short",timeStyle:"short"})}</p></div><strong className="text-gold">{money(order.total)}</strong></div><div className="my-4 space-y-2 border-y border-white/[.06] py-3">{(order.order_items||[]).map(i=><div key={i.id} className="flex justify-between text-sm"><span>{i.quantity}× {i.product_name}</span><span className="text-ivory-mute">{money(i.total)}</span></div>)}</div><div className="space-y-1 text-xs text-ivory-mute"><p>الزبون: <span className="text-ivory">{order.customer_name||"زبون"}</span> · {order.phone}</p><p>الاستلام: <span className="text-ivory">{order.fulfillment==="delivery"?"توصيل":"استلام من المطعم"}</span></p>{order.formatted_address&&<p>العنوان: <span className="text-ivory">{order.formatted_address}</span></p>}{order.notes&&<p>ملاحظة: <span className="text-ivory">{order.notes}</span></p>}</div>{next&&<button disabled={busy} onClick={()=>onStatus(order,next)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-gold px-4 py-3 text-sm font-bold text-bg disabled:opacity-50">{busy?<FiRefreshCw className="animate-spin"/>:<FiCheck/>} {STATUS_LABELS[next]}</button>}{order.status==="pending"&&<button disabled={busy} onClick={()=>onStatus(order,"cancelled")} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-red/20 px-4 py-2 text-xs text-red-200"><FiX/> رفض الطلب</button>}</article>}
function AccessScreen({title,description,userId}:{title:string;description:string;userId?:string}){return <div dir="rtl" className="grid min-h-screen place-items-center bg-bg px-5 text-center text-ivory"><div className="max-w-md rounded-3xl border border-white/[.08] bg-surface p-7"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-gold text-bg"><FiPackage size={24}/></div><h1 className="font-display text-2xl">{title}</h1><p className="mt-2 text-sm leading-6 text-ivory-mute">{description}</p>{userId&&<p className="mt-4 break-all rounded-xl bg-bg p-3 text-[10px] text-ivory-mute">User ID: {userId}</p>}<a href="/" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-gold px-5 py-3 text-sm font-bold text-bg">العودة للموقع <FiArrowRight/></a></div></div>;
